export const PRODUCTS = 'product'
export const AUTH = 'authentication/token'
export const ME = 'authentication/me'
export const CATALOGUE = 'catalogue/'
export const BRAND = 'brand/'
export const RATING = 'rating/'
export const INVENTORY = 'inventory-adjustment'